### ISSUE TITLE
Unable to stat?

### ISSUE THREAD

**Issue by jg-l** [eradman/entr#36]
When I do 
`ls notes/ | entr make generat`

it produces this error
`entr: unable to stat 'file.md'`

Any workarounds?

**Comment by jg-l** [comment]
I don't know why but

`find notes/ | entr make generate` 

works. My issue is solved but maybe this may be a bug

**Comment by eradman** [comment]
The problem is that ls `ls` doesn't include the path, so the filename `file.md`is printed instead of `notes/file.md`

ls(1) is too naive in these cases. You can use shell globing to work around this

```
ls notes/* | entr make generat
```

**Comment by kirk86** [comment]
On OSX 11.5.1 I still get this error when using `ls directory/* | entr` as suggested.
instead `find` solves this issue but for me it creates another one `entr: Too many files listed; the hard limit for your login class is 256. Please consult http://eradman.com/entrproject/limits.html`

Any suggestions or simple fixes here besides downloading `.plist` and hard limits?

The directory I'm monitoring is 15GB in size, it's a gdrive.

**Comment by eradman** [comment]
What version of entr are you using?

Does adjusting the ulimit at the command line change this behavior?

    ulimit -n 65536

**Comment by kirk86** [comment]
> What version of entr are you using?

release: 5.1

> Does adjusting the ulimit at the command line change this behavior?

Nope, still getting `entr: unable to stat`

**Comment by eradman** [comment]
@kirk86 it looks like we need to dig a bit deeper--please create a new Issue with the details

**Comment by simonmichael** [comment]
Thanks for the workarounds. Could entr be a little more user friendly here as follows ?
```
$ ls src | entr make
entr: file 'foo.md' was not found
entr: file 'bar.md' was not found
...
entr: no regular files found to watch
entr: no files had path information; perhaps use find instead of ls ?
```

**Comment by eradman** [comment]
Thanks for the suggestion @simonmichael

I'm thinking about this--the difficulty I have is that sometimes find(1) is a bad choice because it doesn't skip files that start with a `.` by default. In this case `ag -l` works better

**Comment by smhk** [comment]
hello @eradman  !  entr is amazing

there does some to be no solution to simply also looking at folders / recursively??

I use this formulation!

% find ./[^.]* myFolderName myOtherFolderName

Has there been a solution since the discussion above?  Thanks!  JP

**Comment by eradman** [comment]
There is a way to use find(1), but it's somewhat complex:

```
find $PWD -name ".*" -prune -o -print | entr ...
```

This is how it works:

* `$PWD` print the full path to the current directory so that the path does not start with `./`
* `-name ".*" -prune` matches any files or directories that start with a dot and then don't descend
* `-o -print` means print the file name if the previous expression did not match anything. Using `-print` or `-print0` causes all other expressions to not print by default

(You can replace `$PWD` with any pathnames you would like)

**Comment by smhk** [comment]
Ahh!  Incredible, but, my zsh-fu is low.

I was doing this:

`alias superotto="find $PWD -name '.*' -prune -o -print | entr zsh -c \"git commit -am 'otto.5' && git push\""`

actually in my .zshrc file.  It "doesn't work", you oddly get the "too many ..." message.

indeed, you have to make that alias when you're _in the directory you want to be in_.  If you put that alias in .zshrc, say on a Mac, new "Terminal window", the PWD will be the root (or wherever it defaults to when Terminal makes a new window).

Fascinating!  TY!!

**Comment by eradman** [comment]
You're welcome!

This solution is also portable (BSD and GNU versions)

**Comment by smhk** [comment]
Ah, I was just missing a backslash.  **Here's the final formula**, it may help others.

`alias -g fullauto="find \$PWD -name '.*' -prune -o -print | entr zsh -c \"git commit -am 'auto' && git push\""`

The above is one long line that would be in your .zsh file.

Do `% fullauto` and entr will continuously commit/push to git.  **Amazing!**
